"""Add ChurchTheme table

Revision ID: 4ee5cd28887c
Revises: bce5294b8fca
Create Date: 2026-03-11 07:50:38.147855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee5cd28887c'
down_revision = 'bce5294b8fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('church_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('light_primary', sa.String(length=7), nullable=True),
    sa.Column('light_primary_hover', sa.String(length=7), nullable=True),
    sa.Column('light_secondary', sa.String(length=7), nullable=True),
    sa.Column('light_success', sa.String(length=7), nullable=True),
    sa.Column('light_danger', sa.String(length=7), nullable=True),
    sa.Column('light_warning', sa.String(length=7), nullable=True),
    sa.Column('light_info', sa.String(length=7), nullable=True),
    sa.Column('light_bg_main', sa.String(length=7), nullable=True),
    sa.Column('light_bg_card', sa.String(length=7), nullable=True),
    sa.Column('light_text_main', sa.String(length=7), nullable=True),
    sa.Column('light_text_muted', sa.String(length=7), nullable=True),
    sa.Column('light_border', sa.String(length=7), nullable=True),
    sa.Column('light_sidebar_bg', sa.String(length=7), nullable=True),
    sa.Column('light_sidebar_text', sa.String(length=7), nullable=True),
    sa.Column('light_input_bg', sa.String(length=7), nullable=True),
    sa.Column('dark_primary', sa.String(length=7), nullable=True),
    sa.Column('dark_primary_hover', sa.String(length=7), nullable=True),
    sa.Column('dark_secondary', sa.String(length=7), nullable=True),
    sa.Column('dark_success', sa.String(length=7), nullable=True),
    sa.Column('dark_danger', sa.String(length=7), nullable=True),
    sa.Column('dark_warning', sa.String(length=7), nullable=True),
    sa.Column('dark_info', sa.String(length=7), nullable=True),
    sa.Column('dark_bg_main', sa.String(length=7), nullable=True),
    sa.Column('dark_bg_card', sa.String(length=7), nullable=True),
    sa.Column('dark_text_main', sa.String(length=7), nullable=True),
    sa.Column('dark_text_muted', sa.String(length=7), nullable=True),
    sa.Column('dark_border', sa.String(length=7), nullable=True),
    sa.Column('dark_sidebar_bg', sa.String(length=7), nullable=True),
    sa.Column('dark_sidebar_text', sa.String(length=7), nullable=True),
    sa.Column('dark_input_bg', sa.String(length=7), nullable=True),
    sa.Column('logo_light', sa.String(length=255), nullable=True),
    sa.Column('logo_dark', sa.String(length=255), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('church_id')
    )
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.drop_column('logo_light')
        batch_op.drop_column('theme_mode_default')
        batch_op.drop_column('theme_sidebar_bg')
        batch_op.drop_column('logo_dark')
        batch_op.drop_column('theme_secondary')
        batch_op.drop_column('custom_css')
        batch_op.drop_column('theme_primary_hover')
        batch_op.drop_column('theme_primary')
        batch_op.drop_column('theme_sidebar_bg_dark')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_sidebar_bg_dark', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('theme_primary', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('theme_primary_hover', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custom_css', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('theme_secondary', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logo_dark', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('theme_sidebar_bg', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('theme_mode_default', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logo_light', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.drop_table('church_themes')
    # ### end Alembic commands ###
