"""Add theme customization fields to Church

Revision ID: bce5294b8fca
Revises: 3f9e754b5f82
Create Date: 2026-03-09 16:47:21.745629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce5294b8fca'
down_revision = '3f9e754b5f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_primary', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('theme_primary_hover', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('theme_secondary', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('theme_sidebar_bg', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('theme_sidebar_bg_dark', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('theme_mode_default', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('logo_light', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_dark', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('custom_css', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.drop_column('custom_css')
        batch_op.drop_column('logo_dark')
        batch_op.drop_column('logo_light')
        batch_op.drop_column('theme_mode_default')
        batch_op.drop_column('theme_sidebar_bg_dark')
        batch_op.drop_column('theme_sidebar_bg')
        batch_op.drop_column('theme_secondary')
        batch_op.drop_column('theme_primary_hover')
        batch_op.drop_column('theme_primary')

    # ### end Alembic commands ###
